### ISSUE TITLE
Edit link

### ISSUE THREAD

**Issue by amba178** [AgileVentures/MetPlus_tracker#177] opened 2016-01-28 13:21 UTC
As a developer, I want to edit the 'edit' link on home page so that when I click on it should render specific edit page to respective users(AA, JS, CP).

**Comment by patmbolger** [comment] 2016-01-28 13:23
This is a duplicate of #146:

https://waffle.io/AgileVentures/MetPlus_tracker/cards/5672abbcef8e383700269f6d

**Comment by amba178** [comment] 2016-01-28 18:10
@patmbolger :  well I am very confused, initially that was my inclination. But after going through the comments, and ideas that  put forward in #146 look totally something else. If that is the case than, I am very sure we can accomplish the task with line of code and have a fall back link in case something goes wrong while we continue working in development mode. The fall back is temporary thing,  we will eventually remove it.  Sorry if I confuse you, guys.

**Closed** 2016-02-02 22:56 UTC
Labels: bug, enhancement
