### ISSUE TITLE
DRY out forms to edit multiple user

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#169] opened 2016-01-15 23:18 UTC
As a developer 
I need to change the Forms to use reuse views that are shared between forms

**Comment by joaopapereira** [comment] 2016-01-15 23:19
The needed forms to be reviewed are:
Agency Person
Job Seeker

**Comment by patmbolger** [comment] 2016-01-15 23:20
and CompanyPerson

**Comment by sidhene** [comment] 2016-02-23 01:53
and companies/_form
This is a duplicate of company_registrations/_form 

There is also duplication in the cucumber tests for this section - instead of referring to the same view, it is spelled out individually in several tests. This means that when we add or move  a field, that change must be made separately for each repeat.

**Comment by vijayakarumudi** [comment] 2016-02-24 18:47
I am working on dry out form for edit users.

**Comment by vijayakarumudi** [comment] 2016-03-07 22:05
I completed dry out forms  for AgencyPerson,CompanyPerson and JobSeeker. I will create the PR today.

**Closed** 2016-03-11 21:53 UTC
Labels: enhancement
